apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
        - name: upload
          image: gomdadi/upload:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 50055
          envFrom:
            - configMapRef:
                name: upload-env

---
apiVersion: v1
kind: Service
metadata:
  name: upload-rest
spec:
  type: NodePort
  selector:
    app: upload
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30355

---
apiVersion: v1
kind: Service
metadata:
  name: upload-grpc
spec:
  type: ClusterIP
  selector:
    app: upload
  ports:
    - port: 50055
      targetPort: 50055
