apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platformadmin
  template:
    metadata:
      labels:
        app: platformadmin
    spec:
      containers:
        - name: platformadmin
          image: gomdadi/platformadmin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 50054
          envFrom:
            - configMapRef:
                name: platformadmin-env

---
apiVersion: v1
kind: Service
metadata:
  name: platformadmin-rest
spec:
  type: ClusterIP
  selector:
    app: platformadmin
  ports:
    - port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: platformadmin-grpc
spec:
  type: ClusterIP
  selector:
    app: platformadmin
  ports:
    - port: 50054
      targetPort: 50054
