apiVersion: apps/v1
kind: Deployment
metadata:
  name: web3gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web3gateway
  template:
    metadata:
      labels:
        app: web3gateway
    spec:
      containers:
        - name: web3gateway
          image: gomdadi/web3gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50052
          envFrom:
            - configMapRef:
                name: web3gateway-env
---
apiVersion: v1
kind: Service
metadata:
  name: web3gateway-rest
spec:
  type: NodePort
  selector:
    app: web3gateway
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30352
---
apiVersion: v1
kind: Service
metadata:
  name: web3gateway-grpc
spec:
  type: ClusterIP
  selector:
    app: web3gateway
  ports:
    - port: 50052
      targetPort: 50052