apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: purchase
  template:
    metadata:
      labels:
        app: purchase
    spec:
      containers:
        - name: purchase
          image: gomdadi/purchase:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 50056
          envFrom:
            - configMapRef:
                name: purchase-env

---
apiVersion: v1
kind: Service
metadata:
  name: purchase-rest
spec:
  type: NodePort
  selector:
    app: purchase
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30356

---
apiVersion: v1
kind: Service
metadata:
  name: purchase-grpc
spec:
  type: ClusterIP
  selector:
    app: purchase
  ports:
    - port: 50056
      targetPort: 50056
