apiVersion: apps/v1
kind: Deployment
metadata:
  name: management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
        - name: management
          image: gomdadi/management:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
            - containerPort: 50053
          envFrom:
            - configMapRef:
                name: management-env

---
apiVersion: v1
kind: Service
metadata:
  name: management-rest
spec:
  type: NodePort
  selector:
    app: management
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30353

---
apiVersion: v1
kind: Service
metadata:
  name: management-grpc
spec:
  type: ClusterIP
  selector:
    app: management
  ports:
    - port: 50053
      targetPort: 50053
