
name: Deploy Frontend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'manifests/frontend/deployment.yaml'
      - '.github/workflows/deploy-frontend.yml'
  repository_dispatch:
    types: [deploy-frontend]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy deployment file to EC2
        run: |
          scp -o StrictHostKeyChecking=no manifests/frontend/deployment.yaml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/frontend-deployment.yaml

      - name: Deploy to K8s on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            kubectl apply -f /home/${{ secrets.EC2_USER }}/frontend-deployment.yaml
            kubectl rollout restart deployment frontend
          EOF
