name: Deploy Upload to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'manifests/purchase/deployment.yaml'
      - '.github/workflows/deploy-purchase.yml'
  repository_dispatch:
    types: [deploy-purchase]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Generate env config file (purchase-env.yaml)
        run: |
          cat <<EOF > purchase-env.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: purchase-env
          data:
            DB_HOST: "${{ secrets.DB_HOST }}"
            DB_PORT: "${{ secrets.DB_PORT }}"
            DB_USER_NAME: "${{ secrets.DB_USER_NAME }}"
            DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
            DB_NAME: "${{ secrets.DB_NAME }}"
            NODE_ENV: "${{ secrets.NODE_ENV }}"
            USERACCOUNT_INNER: "${{ secrets.USERACCOUNT_INNER }}"
            CLIENT_ORIGIN: "${{ secrets.CLIENT_ORIGIN }}"
            MANAGEMENT_INNER: "${{ secrets.MANAGEMENT_INNER }}"
          EOF

      - name: Copy deployment files to EC2
        run: |
          scp -o StrictHostKeyChecking=no purchase-env.yaml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/
          scp -o StrictHostKeyChecking=no manifests/purchase/deployment.yaml ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

      - name: Deploy to K8s on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            kubectl apply -f /home/${{ secrets.EC2_USER }}/purchase-env.yaml
            kubectl apply -f /home/${{ secrets.EC2_USER }}/deployment.yaml
            kubectl rollout restart deployment purchase
          EOF